CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS roles(id serial PRIMARY KEY, code varchar(40) UNIQUE NOT NULL, name varchar(100) NOT NULL);
CREATE TABLE IF NOT EXISTS users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name varchar(160) NOT NULL, email varchar(180) UNIQUE NOT NULL, password_hash text NOT NULL, role_id int REFERENCES roles(id), active boolean NOT NULL DEFAULT true, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS clients(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ruc varchar(11), business_name varchar(200) NOT NULL, trade_name varchar(200), contact_name varchar(160), contact_email varchar(180), contact_phone varchar(50), active boolean DEFAULT true, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS service_types(id serial PRIMARY KEY, code varchar(20) UNIQUE NOT NULL, name varchar(120) NOT NULL);
CREATE TABLE IF NOT EXISTS projects(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code varchar(40) UNIQUE, client_id uuid REFERENCES clients(id), service_type_id int REFERENCES service_types(id), title varchar(240) NOT NULL, requirement text, brief text, status varchar(50) DEFAULT 'SOLICITUD_RECIBIDA', commercial_owner uuid REFERENCES users(id), start_date date, service_date date, quoted_amount numeric(14,2), approved_amount numeric(14,2), currency varchar(3) DEFAULT 'PEN', operational_closed_at timestamptz, closed_at timestamptz, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS master_phases(id int PRIMARY KEY, block_no int NOT NULL, name varchar(180) NOT NULL, default_area varchar(100));
CREATE TABLE IF NOT EXISTS project_phases(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid REFERENCES projects(id) ON DELETE CASCADE, phase_id int REFERENCES master_phases(id), status varchar(40) DEFAULT 'PENDIENTE', assigned_to uuid REFERENCES users(id), started_at timestamptz, completed_at timestamptz, notes text, UNIQUE(project_id,phase_id));
CREATE TABLE IF NOT EXISTS project_events(id bigserial PRIMARY KEY, project_id uuid REFERENCES projects(id) ON DELETE CASCADE, phase_id int REFERENCES master_phases(id), user_id uuid REFERENCES users(id), event_type varchar(60) NOT NULL, detail jsonb DEFAULT '{}'::jsonb, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS documents(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid REFERENCES projects(id) ON DELETE CASCADE, uploaded_by uuid REFERENCES users(id), category varchar(60) NOT NULL, original_name text NOT NULL, stored_name text NOT NULL, mime_type varchar(120), size_bytes bigint, sha256 varchar(64), storage_key text NOT NULL, status varchar(40) DEFAULT 'PENDIENTE', created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS suppliers(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ruc varchar(11) UNIQUE, business_name varchar(200) NOT NULL, active boolean DEFAULT true);
CREATE TABLE IF NOT EXISTS tax_documents(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid REFERENCES projects(id), document_id uuid REFERENCES documents(id), supplier_id uuid REFERENCES suppliers(id), doc_type varchar(20), issuer_ruc varchar(11), receiver_ruc varchar(11), series varchar(10), number varchar(30), issue_date date, total numeric(14,2), currency varchar(3) DEFAULT 'PEN', sunat_status varchar(40) DEFAULT 'PENDIENTE', sunat_response jsonb, validated_by uuid REFERENCES users(id), validated_at timestamptz, UNIQUE(issuer_ruc,doc_type,series,number));
CREATE TABLE IF NOT EXISTS expenses(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid REFERENCES projects(id), supplier_id uuid REFERENCES suppliers(id), tax_document_id uuid REFERENCES tax_documents(id), category varchar(80), concept text NOT NULL, amount numeric(14,2) NOT NULL, payment_method varchar(50), status varchar(40) DEFAULT 'REGISTRADO', created_by uuid REFERENCES users(id), created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS advances(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid REFERENCES projects(id), recipient uuid REFERENCES users(id), amount numeric(14,2) NOT NULL, rendered_amount numeric(14,2) DEFAULT 0, returned_amount numeric(14,2) DEFAULT 0, status varchar(40) DEFAULT 'PENDIENTE', created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS invoices(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid REFERENCES projects(id), series varchar(10), number varchar(30), amount numeric(14,2), issue_date date, presented_at timestamptz, accepted_at timestamptz, due_date date, status varchar(40) DEFAULT 'PENDIENTE', UNIQUE(series,number));
CREATE TABLE IF NOT EXISTS collections(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), invoice_id uuid REFERENCES invoices(id), amount numeric(14,2) NOT NULL, paid_at timestamptz NOT NULL, reference text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS feedback(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid REFERENCES projects(id), kind varchar(30) NOT NULL, status varchar(40) DEFAULT 'PENDIENTE', comments text, payload jsonb DEFAULT '{}'::jsonb, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_log(id bigserial PRIMARY KEY, user_id uuid REFERENCES users(id), entity varchar(80) NOT NULL, entity_id text, action varchar(80) NOT NULL, before_data jsonb, after_data jsonb, created_at timestamptz DEFAULT now());

INSERT INTO roles(code,name) VALUES ('ADMIN','Administrador General'),('COMERCIAL','Comercial'),('EJECUTIVO','Ejecutivo Comercial'),('PRODUCCION','Producción'),('OPERACIONES','Operaciones'),('FINANZAS','Finanzas / Tesorería'),('CONTABILIDAD','Contabilidad'),('FACTURACION','Facturación'),('GERENCIA','Gerencia') ON CONFLICT DO NOTHING;
INSERT INTO service_types(code,name) VALUES ('EVE','Evento'),('ACT','Activación'),('PUB','Publicidad'),('TPR','Trabajo de producción'),('TIF','Tipo de servicio TIF'),('TMA','Tipo de servicio TMA'),('OTR','Otros') ON CONFLICT DO NOTHING;

INSERT INTO master_phases(id,block_no,name,default_area) VALUES
(1,1,'Contacto con cliente','Comercial'),(2,1,'Registro cliente y contacto','Comercial'),(3,1,'Reunión y presentación','Comercial'),(4,1,'Levantamiento requerimiento','Comercial'),(5,1,'Brief cliente','Comercial'),(6,1,'Validación brief','Comercial'),(7,1,'Derivación a Operaciones y Producción','Comercial'),
(8,2,'Asignación productor','Producción'),(9,2,'Confirmación recepción','Producción'),(10,2,'Revisión técnica/operativa','Producción'),(11,2,'Solicitud información adicional','Producción'),(12,2,'Clasificación servicio','Ejecutivo Comercial'),(13,2,'Definición áreas involucradas','Producción'),(14,2,'Apertura expediente proyecto','Producción'),(15,2,'Solicitud costos','Producción'),(16,2,'Creatividad/diseño preliminar','Producción'),(17,2,'Armado interno','Producción'),(18,2,'Preparación cotización cliente','Producción'),(19,2,'Validación interna','Producción'),
(20,3,'Envío cotización','Comercial'),(21,3,'Esperando respuesta','Comercial'),(22,3,'Solicitud cambios','Comercial'),(23,3,'Recotización / nueva versión','Comercial'),(24,3,'Negociación comercial','Comercial'),(25,3,'Proyecto desaprobado','Comercial'),(26,3,'Proyecto aprobado','Comercial'),(27,3,'Formalización comercial','Comercial'),
(28,4,'Creación ficha proyecto','Operaciones'),(29,4,'Codificación proyecto','Operaciones'),(30,4,'Planificación ejecución','Operaciones'),(31,4,'Contratación / confirmación proveedores','Producción'),(32,4,'Solicitud anticipos / pagos previos','Producción'),(33,4,'Diseño final / artes','Producción'),(34,4,'Logística / almacén','Operaciones'),(35,4,'Ejecución proyecto','Operaciones'),(36,4,'Incidencias / adicionales','Operaciones'),
(37,5,'Registro gastos','Finanzas'),(38,5,'Anticipo / fondo por rendir','Finanzas'),(39,5,'Rendición','Finanzas'),(40,5,'Devolución saldo','Finanzas'),(41,5,'Reembolso','Finanzas'),(42,5,'Cuenta por pagar proveedor','Finanzas'),(43,5,'Programación pago','Tesorería'),(44,5,'Ejecución pago + voucher','Tesorería'),
(45,6,'Validación del comprobante','Contabilidad'),(46,6,'Detracción / obligaciones tributarias','Contabilidad'),(47,6,'Registro contable','Contabilidad'),(48,6,'Corrección / nota de crédito','Contabilidad'),
(49,7,'Cierre operativo','Operaciones'),(50,7,'Feedback post ejecución','Operaciones'),(51,7,'Encuesta satisfacción cliente','Ejecutivo Comercial'),(52,7,'Consolidación sustentos','Producción'),(53,7,'Liquidación proyecto','Producción'),(54,7,'Interno vs Real','Producción'),(55,7,'Revisión liquidación','Operaciones'),(56,7,'Conciliación financiera','Finanzas'),(57,7,'Conciliación contable','Contabilidad'),
(58,8,'Validación para facturar','Facturación'),(59,8,'Emisión factura cliente','Facturación'),(60,8,'Presentación factura','Facturación'),(61,8,'Observación factura','Facturación'),(62,8,'Aceptación factura','Facturación'),
(63,9,'Cuenta por cobrar','Finanzas'),(64,9,'Seguimiento cobranza','Finanzas'),(65,9,'Cobro parcial','Finanzas'),(66,9,'Cobro total','Finanzas'),(67,9,'Validación cierre','Operaciones'),(68,9,'Conciliado - listo para cerrar','Operaciones'),(69,9,'Cierre código','Operaciones'),(70,9,'Archivo proyecto','Operaciones'),(71,9,'Cierre proyecto','Operaciones'),(72,9,'Histórico / análisis','Gerencia') ON CONFLICT (id) DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_projects_client ON projects(client_id); CREATE INDEX IF NOT EXISTS idx_documents_project ON documents(project_id); CREATE INDEX IF NOT EXISTS idx_expenses_project ON expenses(project_id); CREATE INDEX IF NOT EXISTS idx_events_project ON project_events(project_id,created_at DESC);
